if(NOT DEFINED TEST_PROGRAM OR NOT DEFINED OUTPUT_PARENT)
  message(FATAL_ERROR "test program and output parent required")
endif()
file(MAKE_DIRECTORY "${OUTPUT_PARENT}")
string(RANDOM LENGTH 24 ALPHABET 0123456789abcdef suffix)
set(output "${OUTPUT_PARENT}/run-${suffix}")
set(args "${output}")
if(DEFINED THERMAL_FILE AND DEFINED BEAM_FILE)
  list(APPEND args "${THERMAL_FILE}" "${BEAM_FILE}")
endif()
execute_process(COMMAND "${TEST_PROGRAM}" ${args} RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "diagnostic test failed: ${result}; evidence: ${output}")
endif()
