from pathlib import Path
import mpmath as mp
mp.mp.dps=45
alpha=1/mp.mpf('137.035999084');hc=mp.mpf('197.3269804');mass=mp.mpf('3727.3794118')
rows=[]
for ch in range(5):
 l=[1,2,3,0,2][ch];mu=mass*(mp.mpf(2)/3 if ch<3 else mp.mpf(1)/2);a=mp.mpf('5.1' if ch<3 else '4.5');z=8 if ch<3 else 4
 for energy in ['.001','.0017','.1','.743','3.129','7.31','12']:
  E=mp.mpf(energy);eta=z*alpha*mp.sqrt(mu/(2*E));rho=a*mp.sqrt(2*mu*E)/hc
  F=mp.coulombf(l,eta,rho);G=mp.coulombg(l,eta,rho)
  fp=mp.diff(lambda r:mp.coulombf(l,eta,r),rho);gp=mp.diff(lambda r:mp.coulombg(l,eta,r),rho)
  assert abs(fp*G-F*gp-1)<mp.mpf('1e-30')
  den=F*F+G*G;phase=mp.im(mp.loggamma(l+1+1j*eta))-mp.atan2(F,G)
  v=[E,mp.log(rho/den),rho*(F*fp+G*gp)/den,mp.cos(phase),mp.sin(phase)]
  rows.append('{'+str(ch)+','+','.join(mp.nstr(x,19) for x in v)+'}')
text='// Generated by tools/generate_nuclear_reference.py with mpmath1.3.0 at45digits.\nstruct NuclearReference { int channel; double E,logP,S,re,im; };\nconst NuclearReference nuclear_references[]={\n'+',\n'.join(rows)+'\n};\n'
Path(__file__).resolve().parents[1].joinpath('tests/nuclear_coulomb_reference.inc').write_text(text)
print('generated',len(rows),'independent reference points',flush=True)
