cmake_minimum_required(VERSION 3.16)
project(birth_table_consumer LANGUAGES C CXX Fortran)
include("${PB11_INSTALL}/lib/cmake/pb11_reaction/pb11Targets.cmake")
add_executable(c11 main.c)
set_target_properties(c11 PROPERTIES C_STANDARD 11 C_STANDARD_REQUIRED YES LINKER_LANGUAGE CXX)
target_link_libraries(c11 PRIVATE pb11::pb11)
add_executable(fortran_test main.f90)
set_target_properties(fortran_test PROPERTIES LINKER_LANGUAGE Fortran)
target_link_libraries(fortran_test PRIVATE pb11::fusion_birth_table_fortran pb11::fusion_coupled_thermal_fortran)
